FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_VENV=.venv
ENV PATH="/app/.venv/bin:$PATH"

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev

# Copy the app source
ADD . /app

# Optional: install the actual project (editable)
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install -e .

EXPOSE 8080

ENTRYPOINT []

CMD ["uvicorn", "Rag_agents.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
